# f=open('fruits.txt')
# content = f.read()
# print(content)

# ----------------------
# f=open('fruits.txt',"w")
# # content = f.read()
# # print(content)
# f.write("Grape\n")
# f.write("Mango\n")
# f.write("Kiwi\n")
# f.close()
# f=open('fruits.txt',"r+")
# # content=f.read()
# print(f.read())

# ----------------------
# f=open('fruits.txt',"a")
# # content = f.read()
# # print(content)
# f.write("Apple\n")
# f.write("Orange\n")
# f.write("Green Apple\n")
# f.close()
# f=open('fruits.txt',"r+")
# # content=f.read()
# print(f.read())

# ----------------------
f=open('fruits.txt',"a")
# content = f.read()
# print(content)
f.write("Apple\n")
f.write("Orange\n")
f.write("Green Apple\n")
f.close()
f=open('fruits.txt',"r+")
# content=f.read()
print(f.readline())
